### ISSUE TITLE
JavaScript doesn't return an Array in zeebe

### ISSUE THREAD

**Issue by PedroKravetz** [camunda-community-hub/script-connector#216]
When you try to return a array in zeebe using JavaScript, it doesn't return an Array. Here is an example:
`return ["a", "b"];`
in zeebe, it returns {"0": "a", "1": "b"};, he put the index of the array inside a json and doesn't return a array.
This only happens in JavaScript, in Groovy, it gives back the array as it is.

**Comment by saig0** [comment]
@PedroKravetz thank you for reporting :+1: 

It seems to be a known issue: https://stackoverflow.com/questions/22492641/java8-js-nashorn-convert-array-to-java-array

I guess that it would make sense to migrate to GraalVM JS (#170). 

Since this is currently not my focus (as a maintainer of this repo), I would be happy to receive contributions from the community :rocket:

**Comment by jonathanlukas** [comment]
Hello @PedroKravetz , as the migration to graalvm js is now done, could you please confirm that the issue is resolved?
